# Generated by Django 6.0.6 on 2026-06-24 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HabitatZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('health_status', models.CharField(default='Healthy', max_length=50)),
                ('habitat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='safari_app.habitatzone')),
            ],
        ),
        migrations.CreateModel(
            name='TourGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('shift_start', models.TimeField()),
                ('shift_end', models.TimeField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave')], default='Active', max_length=20)),
                ('assigned_zones', models.ManyToManyField(related_name='guides', to='safari_app.habitatzone')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=100)),
                ('booking_date', models.DateField()),
                ('slot_time', models.TimeField()),
                ('vehicle_number', models.CharField(max_length=20)),
                ('pricing_tier', models.CharField(choices=[('Basic', 'Basic'), ('Standard', 'Standard'), ('Premium', 'Premium')], default='Standard', max_length=20)),
                ('assigned_guide', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='safari_app.tourguide')),
            ],
        ),
    ]
