# Generated by Django 6.0.6 on 2026-06-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safari_app', '0004_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourguide',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourguide',
            name='profile_image',
            field=models.URLField(default='https://static.vecteezy.com/system/resources/previews/036/190/419/original/business-man-blank-profile-image-with-beard-vector.jpg', max_length=500),
        ),
    ]
