# Generated by Django 6.0.6 on 2026-06-25 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safari_app', '0006_booking_contact_email_booking_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='contact_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='booking',
            name='contact_phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 10 digits and start with 07.', regex='^07\\d{8}$')]),
        ),
    ]
